name: open_eye
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  curved_navigation_bar:
  animated_toggle_switch:
  speech_to_text:
  avatar_glow:
  flutter_tts:
  shared_preferences:
  flutter_phone_direct_caller:
  camera:
  tflite:
  sqflite:
  path:
  http:
  google_mlkit_text_recognition:
  permission_handler:
  cupertino_icons:
  agora_rtc_engine: ^5.2.0
  firebase_auth:
  firebase_core:
#  intl:
#  timezone:
#  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
    - assets/json/
